// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzCks3ol0wamqeHIXpw3pWzni3R8sCcg',
    appId: '1:460775438496:web:664c2186e7c43f2eb2b1c5',
    messagingSenderId: '460775438496',
    projectId: 'make-it-98abf',
    authDomain: 'make-it-98abf.firebaseapp.com',
    storageBucket: 'make-it-98abf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKO2z9-2e7gyabj0QdNro9F_xQuo8QZY',
    appId: '1:460775438496:android:4a75de8fea5f1ddeb2b1c5',
    messagingSenderId: '460775438496',
    projectId: 'make-it-98abf',
    storageBucket: 'make-it-98abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoe6WIwgcthSZah6hIjxdT55Fie65NvN0',
    appId: '1:460775438496:ios:85620c15a23107b4b2b1c5',
    messagingSenderId: '460775438496',
    projectId: 'make-it-98abf',
    storageBucket: 'make-it-98abf.appspot.com',
    iosBundleId: 'com.example.makeIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoe6WIwgcthSZah6hIjxdT55Fie65NvN0',
    appId: '1:460775438496:ios:80ff9e0c1decddedb2b1c5',
    messagingSenderId: '460775438496',
    projectId: 'make-it-98abf',
    storageBucket: 'make-it-98abf.appspot.com',
    iosBundleId: 'com.example.makeIt.RunnerTests',
  );
}
